production:
  adapter: postgresql
  database: bettermeans_prod
  host: localhost
  username: xxxxxx
  password: xxxxxx
  encoding: utf8

development:
  adapter: postgresql
  database: bettermeans_dev
  host: localhost
  min_messages: WARNING
  username: xxxxx
  password: xxxxx

test: &TEST
  adapter: postgresql
  database: bettermeans_test
  host: localhost
  min_messages: WARNING
  username: postgres
  password: postgres

test_pgsql:
  adapter: postgresql
  database: bettermeans_test
  host: localhost
  min_messages: WARNING
  username: postgres
  password: postgres

test_sqlite3:
  adapter: sqlite3
  dbfile: db/test.db

demo:
  adapter: sqlite3
  dbfile: db/demo.db


cucumber:
  <<: *TEST

selenium:
  <<: *TEST
