# Outgoing email settings

production:
  delivery_method: :smtp
  smtp_settings:
   address: smtp.sendgrid.net
   port: 25
   domain: ejecutivo.comunas.org.ar
   authentication: :login
   user_name: "eudemocracia" 
   password: "democraciadirecta"

development:
  delivery_method: :smtp
  smtp_settings:
    tls: true
    address: "smtp.sendgrid.net"
    port: '587'
    domain: "smtp.sendgrid.net"
    authentication: :plain
    user_name: "xxxxxxxx"
    password: "xxxxxxxxxxx"

test:
  delivery_method: :test


#development:
#  delivery_method: :smtp
#  smtp_settings:
#    address: NOEMAILSENTOUT
#    port: 26
#    domain: heroku.com
#    authentication: :login
#    user_name: ac4366312345
#    password: ctvw9zfra12345
